# Ex07 Getting and Knowing your Data with Pandas

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [6]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [7]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user' , delimiter = "|" , index_col = 'user_id' )
users

#for split in users:
 #   split = users(split.split())
    
#split
#s = users['user_id|age|gender|occupation|zip_code'].str.split(' ').apply().stack()
#s.index = s.index.droplevel(-1)
#s.name = 'Seatblocks'
#s

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107
26        49      M       engineer    21044
27        40      F      librarian    30030
28        32      M         writer    55369
29        41      M     programmer    94043
30         7      M        student    55436
31        24      M         artist    10003
32        28      F        student    78741
33        23      M        student    27510
34        38      F  administrator    42141
35        20      F      homemaker    42459
36        19      F        student    93117
37        23      M        student    55105
38        28      F          other    54467
39        41      M  entertainment    01040
40        38      M      scientist    27514
41        33      M       engineer    80525
42        30      M  administrator    17870
43        29      F      librarian    20854
44        26      M     technician    46260
45        29      M     programmer    50233
46        27      F      marketing    46538
47        53      M      marketing    07102
48        45      M  administrator    12550
49        23      F        student    76111
50        21      M         writer    52245
51        28      M       educator    16509
52        18      F        student    55105
53        26      M     programmer    55414
54        22      M      executive    66315
55        37      M     programmer    01331
56        25      M      librarian    46260
57        16      M           none    84010
58        27      M     programmer    52246
59        49      M       educator    08403
60        50      M     healthcare    06472
61        36      M       engineer    30040
62        27      F  administrator    97214
63        31      M      marketing    75240
64        32      M       educator    43202
65        51      F       educator    48118
66        23      M        student    80521
67        17      M        student    60402
68        19      M        student    22904
69        24      M       engineer    55337
70        27      M       engineer    60067
71        39      M      scientist    98034
72        48      F  administrator    73034
73        24      M        student    41850
74        39      M      scientist    T8H1N
75        24      M  entertainment    08816
76        20      M        student    02215
77        30      M     technician    29379
78        26      M  administrator    61801
79        39      F  administrator    03755
80        34      F  administrator    52241
81        21      M        student    21218
82        50      M     programmer    22902
83        40      M          other    44133
84        32      M      executive    55369
85        51      M       educator    20003
86        26      M  administrator    46005
87        47      M  administrator    89503
88        49      F      librarian    11701
89        43      F  administrator    68106
90        60      M       educator    78155
91        55      M      marketing    01913
92        32      M  entertainment    80525
93        48      M      executive    23112
94        26      M        student    71457
95        31      M  administrator    10707
96        25      F         artist    75206
97        43      M         artist    98006
98        49      F      executive    90291
99        20      M        student    63129
100       36      M      executive    90254
101       15      M        student    05146
102       38      M     programmer    30220
103       26      M        student    55108
104       27      M        student    55108
105       24      M       engineer    94043
106       61      M        retired    55125
107       39      M      scientist    60466
108       44      M       educator    63130
109       29      M          other    55423
110       19      M        student    77840
111       57      M       engineer    90630
112       30      M       salesman    60613
113       47      M      executive    95032
114       27      M     programmer    75013
115       31      M       engineer    17110
116       40      M     healthcare    97232
117       20      M        student    16125
118       21      M  administrator    90210
119       32      M     programmer    67401
120       47      F          other    06260
121       54      M      librarian    99603
122       32      F         writer    22206
123       48      F         artist    20008
124       34      M        student    60615
125       30      M         lawyer    22202
126       28      F         lawyer    20015
127       33      M           none    73439
128       24      F      marketing    20009
129       36      F      marketing    07039
130       20      M           none    60115
131       59      F  administrator    15237
132       24      M          other    94612
133       53      M       engineer    78602
134       31      M     programmer    80236
135       23      M        student    38401
136       51      M          other    97365
137       50      M       educator    84408
138       46      M         doctor    53211
139       20      M        student    08904
140       30      F        student    32250
141       49      M     programmer    36117
142       13      M          other    48118
143       42      M     technician    08832
144       53      M     programmer    20910
145       31      M  entertainment    V3N4P
146       45      M         artist    83814
147       40      F      librarian    02143
148       33      M       engineer    97006
149       35      F      marketing    17325
150       20      F         artist    02139
151       38      F  administrator    48103
152       33      F       educator    68767
153       25      M        student    60641
154       25      M        student    53703
155       32      F          other    11217
156       25      M       educator    08360
157       57      M       engineer    70808
158       50      M       educator    27606
159       23      F        student    55346
160       27      M     programmer    66215
161       50      M         lawyer    55104
162       25      M         artist    15610
163       49      M  administrator    97212
164       47      M     healthcare    80123
165       20      F          other    53715
166       47      M       educator    55113
167       37      M          other    L9G2B
168       48      M          other    80127
169       52      F          other    53705
170       53      F     healthcare    30067
171       48      F       educator    78750
172       55      M      marketing    22207
173       56      M          other    22306
174       30      F  administrator    52302
175       26      F      scientist    21911
176       28      M      scientist    07030
177       20      M     programmer    19104
178       26      M          other    49512
179       15      M  entertainment    20755
180       22      F  administrator    60202
181       26      M      executive    21218
182       36      M     programmer    33884
183       33      M      scientist    27708
184       37      M      librarian    76013
185       53      F      librarian    97403
186       39      F      executive    00000
187       26      M       educator    16801
188       42      M        student    29440
189       32      M         artist    95014
190       30      M  administrator    95938
191       33      M  administrator    95161
192       42      M       educator    90840
193       29      M        student    49931
194       38      M  administrator    02154
195       42      M      scientist    93555
196       49      M         writer    55105
197       55      M     technician    75094
198       21      F        student    55414
199       30      M         writer    17604
200       40      M     programmer    93402
201       27      M         writer    E2A4H
202       41      F       educator    60201
203       25      F        student    32301
204       52      F      librarian    10960
205       47      M         lawyer    06371
206       14      F        student    53115
207       39      M      marketing    92037
208       43      M       engineer    01720
209       33      F       educator    85710
210       39      M       engineer    03060
211       66      M       salesman    32605
212       49      F       educator    61401
213       33      M      executive    55345
214       26      F      librarian    11231
215       35      M     programmer    63033
216       22      M       engineer    02215
217       22      M          other    11727
218       37      M  administrator    06513
219       32      M     programmer    43212
220       30      M      librarian    78205
221       19      M        student    20685
222       29      M     programmer    27502
223       19      F        student    47906
224       31      F       educator    43512
225       51      F  administrator    58202
226       28      M        student    92103
227       46      M      executive    60659
228       21      F        student    22003
229       29      F      librarian    22903
230       28      F        student    14476
231       48      M      librarian    01080
232       45      M      scientist    99709
233       38      M       engineer    98682
234       60      M        retired    94702
235       37      M       educator    22973
236       44      F         writer    53214
237       49      M  administrator    63146
238       42      F  administrator    44124
239       39      M         artist    95628
240       23      F       educator    20784
241       26      F        student    20001
242       33      M       educator    31404
243       33      M       educator    60201
244       28      M     technician    80525
245       22      M        student    55109
246       19      M        student    28734
247       28      M       engineer    20770
248       25      M        student    37235
249       25      M        student    84103
250       29      M      executive    95110
251       28      M         doctor    85032
252       42      M       engineer    07733
253       26      F      librarian    22903
254       44      M       educator    42647
255       23      M  entertainment    07029
256       35      F           none    39042
257       17      M        student    77005
258       19      F        student    77801
259       21      M        student    48823
260       40      F         artist    89801
261       28      M  administrator    85202
262       19      F        student    78264
263       41      M     programmer    55346
264       36      F         writer    90064
265       26      M      executive    84601
266       62      F  administrator    78756
267       23      M       engineer    83716
268       24      M       engineer    19422
269       31      F      librarian    43201
270       18      F        student    63119
271       51      M       engineer    22932
272       33      M      scientist    53706
273       50      F          other    10016
274       20      F        student    55414
275       38      M       engineer    92064
276       21      M        student    95064
277       35      F  administrator    55406
278       37      F      librarian    30033
279       33      M     programmer    85251
280       30      F      librarian    22903
281       15      F        student    06059
282       22      M  administrator    20057
283       28      M     programmer    55305
284       40      M      executive    92629
285       25      M     programmer    53713
286       27      M        student    15217
287       21      M       salesman    31211
288       34      M      marketing    23226
289       11      M           none    94619
290       40      M       engineer    93550
291       19      M        student    44106
292       35      F     programmer    94703
293       24      M         writer    60804
294       34      M     technician    92110
295       31      M       educator    50325
296       43      F  administrator    16803
297       29      F       educator    98103
298       44      M      executive    01581
299       29      M         doctor    63108
300       26      F     programmer    55106
301       24      M        student    55439
302       42      M       educator    77904
303       19      M        student    14853
304       22      F        student    71701
305       23      M     programmer    94086
306       45      M          other    73132
307       25      M        student    55454
308       60      M        retired    95076
309       40      M      scientist    70802
310       37      M       educator    91711
311       32      M     technician    73071
312       48      M          other    02110
313       41      M      marketing    60035
314       20      F        student    08043
315       31      M       educator    18301
316       43      F          other    77009
317       22      M  administrator    13210
318       65      M        retired    06518
319       38      M     programmer    22030
320       19      M        student    24060
321       49      F       educator    55413
322       20      M        student    50613
323       21      M        student    19149
324       21      F        student    02176
325       48      M     technician    02139
326       41      M  administrator    15235
327       22      M        student    11101
328       51      M  administrator    06779
329       48      M       educator    01720
330       35      F       educator    33884
331       33      M  entertainment    91344
332       20      M        student    40504
333       47      M          other    V0R2M
334       32      M      librarian    30002
335       45      M      executive    33775
336       23      M       salesman    42101
337       37      M      scientist    10522
338       39      F      librarian    59717
339       35      M         lawyer    37901
340       46      M       engineer    80123
341       17      F        student    44405
342       25      F          other    98006
343       43      M       engineer    30093
344       30      F      librarian    94117
345       28      F      librarian    94143
346       34      M          other    76059
347       18      M        student    90210
348       24      F        student    45660
349       68      M        retired    61455
350       32      M        student    97301
351       61      M       educator    49938
352       37      F     programmer    55105
353       25      M      scientist    28480
354       29      F      librarian    48197
355       25      M        student    60135
356       32      F      homemaker    92688
357       26      M      executive    98133
358       40      M       educator    10022
359       22      M        student    61801
360       51      M          other    98027
361       22      M        student    44074
362       35      F      homemaker    85233
363       20      M        student    87501
364       63      M       engineer    01810
365       29      M         lawyer    20009
366       20      F        student    50670
367       17      M        student    37411
368       18      M        student    92113
369       24      M        student    91335
370       52      M         writer    08534
371       36      M       engineer    99206
372       25      F        student    66046
373       24      F          other    55116
374       36      M      executive    78746
375       17      M  entertainment    37777
376       28      F          other    10010
377       22      M        student    18015
378       35      M        student    02859
379       44      M     programmer    98117
380       32      M       engineer    55117
381       33      M         artist    94608
382       45      M       engineer    01824
383       42      M  administrator    75204
384       52      M     programmer    45218
385       36      M         writer    10003
386       36      M       salesman    43221
387       33      M  entertainment    37412
388       31      M          other    36106
389       44      F         writer    83702
390       42      F         writer    85016
391       23      M        student    84604
392       52      M         writer    59801
393       19      M        student    83686
394       25      M  administrator    96819
395       43      M          other    44092
396       57      M       engineer    94551
397       17      M        student    27514
398       40      M          other    60008
399       25      M          other    92374
400       33      F  administrator    78213
401       46      F     healthcare    84107
402       30      M       engineer    95129
403       37      M          other    06811
404       29      F     programmer    55108
405       22      F     healthcare    10019
406       52      M       educator    93109
407       29      M       engineer    03261
408       23      M        student    61755
409       48      M  administrator    98225
410       30      F         artist    94025
411       34      M       educator    44691
412       25      M       educator    15222
413       55      M       educator    78212
414       24      M     programmer    38115
415       39      M       educator    85711
416       20      F        student    92626
417       27      F          other    48103
418       55      F           none    21206
419       37      M         lawyer    43215
420       53      M       educator    02140
421       38      F     programmer    55105
422       26      M  entertainment    94533
423       64      M          other    91606
424       36      F      marketing    55422
425       19      M        student    58644
426       55      M       educator    01602
427       51      M         doctor    85258
428       28      M        student    55414
429       27      M        student    29205
430       38      M      scientist    98199
431       24      M      marketing    92629
432       22      M  entertainment    50311
433       27      M         artist    11211
434       16      F        student    49705
435       24      M       engineer    60007
436       30      F  administrator    17345
437       27      F          other    20009
438       51      F  administrator    43204
439       23      F  administrator    20817
440       30      M          other    48076
441       50      M     technician    55013
442       22      M        student    85282
443       35      M       salesman    33308
444       51      F         lawyer    53202
445       21      M         writer    92653
446       57      M       educator    60201
447       30      M  administrator    55113
448       23      M  entertainment    10021
449       23      M      librarian    55021
450       35      F       educator    11758
451       16      M        student    48446
452       35      M  administrator    28018
453       18      M        student    06333

In [49]:
xx = str(users["user_id|age|gender|occupation|zip_code"][0])
xx

'1|24|M|technician|85711'

### Step 4. See the first 25 entries

In [51]:
users[:25]

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

In [52]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [5]:
len(users)

943

### Step 7. What is the number of columns in the dataset?

In [6]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [7]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [12]:
users.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [9]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [11]:
pd.set_option('display.max_rows',None)
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
6          executive
7      administrator
8      administrator
9            student
10            lawyer
11             other
12             other
13          educator
14         scientist
15          educator
16     entertainment
17        programmer
18             other
19         librarian
20         homemaker
21            writer
22            writer
23            artist
24            artist
25          engineer
26          engineer
27         librarian
28            writer
29        programmer
30           student
31            artist
32           student
33           student
34     administrator
35         homemaker
36           student
37           student
38             other
39     entertainment
40         scientist
41          engineer
42     administrator
43         librarian
44        technician
45        programmer
46         marketing
47         marketing
48     administrator
49           student
50            writer
51          educator
52           student
53        programmer
54         executive
55        programmer
56         librarian
57              none
58        programmer
59          educator
60        healthcare
61          engineer
62     administrator
63         marketing
64          educator
65          educator
66           student
67           student
68           student
69          engineer
70          engineer
71         scientist
72     administrator
73           student
74         scientist
75     entertainment
76           student
77        technician
78     administrator
79     administrator
80     administrator
81           student
82        programmer
83             other
84         executive
85          educator
86     administrator
87     administrator
88         librarian
89     administrator
90          educator
91         marketing
92     entertainment
93         executive
94           student
95     administrator
96            artist
97            artist
98         executive
99           student
100        executive
101          student
102       programmer
103          student
104          student
105         engineer
106          retired
107        scientist
108         educator
109            other
110          student
111         engineer
112         salesman
113        executive
114       programmer
115         engineer
116       healthcare
117          student
118    administrator
119       programmer
120            other
121        librarian
122           writer
123           artist
124          student
125           lawyer
126           lawyer
127             none
128        marketing
129        marketing
130             none
131    administrator
132            other
133         engineer
134       programmer
135          student
136            other
137         educator
138           doctor
139          student
140          student
141       programmer
142            other
143       technician
144       programmer
145    entertainment
146           artist
147        librarian
148         engineer
149        marketing
150           artist
151    administrator
152         educator
153          student
154          student
155            other
156         educator
157         engineer
158         educator
159          student
160       programmer
161           lawyer
162           artist
163    administrator
164       healthcare
165            other
166         educator
167            other
168            other
169            other
170       healthcare
171         educator
172        marketing
173            other
174    administrator
175        scientist
176        scientist
177       programmer
178            other
179    entertainment
180    administrator
181        executive
182       programmer
183        scientist
184        librarian
185        librarian
186        executive
187         educator
188          student
189           artist
190    administrator
191    administrator
192         educator
193          student
194    administrator
195        scientist
196           writer
197       technician
198          student
199           writer
200       programmer
201           writer
202         educator
203          student
204        librarian
205           lawyer
206          student
207        marketing
208         engineer
209         educator
210         engineer
211         salesman
212         educator
213        executive
214        librarian
215       programmer
216         engineer
217            other
218    administrator
219       programmer
220        librarian
221          student
222       programmer
223          student
224         educator
225    administrator
226          student
227        executive
228          student
229        librarian
230          student
231        librarian
232        scientist
233         engineer
234          retired
235         educator
236           writer
237    administrator
238    administrator
239           artist
240         educator
241          student
242         educator
243         educator
244       technician
245          student
246          student
247         engineer
248          student
249          student
250        executive
251           doctor
252         engineer
253        librarian
254         educator
255    entertainment
256             none
257          student
258          student
259          student
260           artist
261    administrator
262          student
263       programmer
264           writer
265        executive
266    administrator
267         engineer
268         engineer
269        librarian
270          student
271         engineer
272        scientist
273            other
274          student
275         engineer
276          student
277    administrator
278        librarian
279       programmer
280        librarian
281          student
282    administrator
283       programmer
284        executive
285       programmer
286          student
287         salesman
288        marketing
289             none
290         engineer
291          student
292       programmer
293           writer
294       technician
295         educator
296    administrator
297         educator
298        executive
299           doctor
300       programmer
301          student
302         educator
303          student
304          student
305       programmer
306            other
307          student
308          retired
309        scientist
310         educator
311       technician
312            other
313        marketing
314          student
315         educator
316            other
317    administrator
318          retired
319       programmer
320          student
321         educator
322          student
323          student
324          student
325       technician
326    administrator
327          student
328    administrator
329         educator
330         educator
331    entertainment
332          student
333            other
334        librarian
335        executive
336         salesman
337        scientist
338        librarian
339           lawyer
340         engineer
341          student
342            other
343         engineer
344        librarian
345        librarian
346            other
347          student
348          student
349          retired
350          student
351         educator
352       programmer
353        scientist
354        librarian
355          student
356        homemaker
357        executive
358         educator
359          student
360            other
361          student
362        homemaker
363          student
364         engineer
365           lawyer
366          student
367          student
368          student
369          student
370           writer
371         engineer
372          student
373            other
374        executive
375    entertainment
376            other
377          student
378          student
379       programmer
380         engineer
381           artist
382         engineer
383    administrator
384       programmer
385           writer
386         salesman
387    entertainment
388            other
389           writer
390           writer
391          student
392           writer
393          student
394    administrator
395            other
396         engineer
397          student
398            other
399            other
400    administrator
401       healthcare
402         engineer
403            other
404       programmer
405       healthcare
406         educator
407         engineer
408          student
409    administrator
410           artist
411         educator
412         educator
413         educator
414       programmer
415         educator
416          student
417            other
418             none
419           lawyer
420         educator
421       programmer
422    entertainment
423            other
424        marketing
425          student
426         educator
427           doctor
428          student
429          student
430        scientist
431        marketing
432    entertainment
433           artist
434          student
435         engineer
436    administrator
437            other
438    administrator
439    administrator
440            other
441       technician
442          student
443         salesman
444           lawyer
445           writer
446         educator
447    administrator
448    entertainment
449        librarian
450         educator
451          student
452    administrator
453          student
454            other
455    administrator
456       technician
457         salesman
458       technician
459          student
460            other
461          student
462          student
463       healthcare
464           writer
465            other
466          student
467         engineer
468         engineer
469         educator
470       programmer
471          student
472          student
473          student
474        executive
475       programmer
476          student
477          student
478            other
479         educator
480          retired
481          retired
482          student
483        scientist
484          student
485         educator
486         educator
487         engineer
488       technician
489            other
490           artist
491           writer
492         educator
493         engineer
494    administrator
495         engineer
496          student
497          student
498           writer
499       programmer
500    administrator
501          student
502          student
503           writer
504           writer
505            other
506       programmer
507           writer
508        marketing
509    administrator
510            other
511          student
512            other
513    administrator
514       programmer
515        marketing
516        librarian
517          student
518           writer
519            other
520       healthcare
521          student
522         engineer
523    administrator
524         educator
525    administrator
526        marketing
527        librarian
528          student
529    administrator
530         engineer
531         salesman
532          student
533        librarian
534          student
535         educator
536         engineer
537         engineer
538        scientist
539    administrator
540         engineer
541          student
542          student
543        scientist
544            other
545       technician
546        executive
547         educator
548           writer
549        scientist
550          student
551       programmer
552            other
553         educator
554        scientist
555         educator
556         educator
557           writer
558           writer
559        executive
560          student
561         engineer
562    administrator
563        librarian
564          retired
565          student
566          student
567    entertainment
568         educator
569         educator
570         educator
571           artist
572         educator
573          retired
574         educator
575        marketing
576        executive
577          student
578    administrator
579         educator
580          student
581            other
582          student
583         engineer
584          student
585        librarian
586          student
587            other
588          student
589           lawyer
590         educator
591        librarian
592          student
593         educator
594         educator
595       programmer
596           artist
597            other
598        marketing
599          student
600       programmer
601           artist
602            other
603       programmer
604         educator
605         engineer
606       programmer
607       healthcare
608            other
609          student
610          student
611        librarian
612         educator
613        marketing
614         educator
615         educator
616        scientist
617           writer
618          student
619          student
620           writer
621          student
622       programmer
623         educator
624          student
625       programmer
626        scientist
627         engineer
628             none
629            other
630       healthcare
631          student
632          student
633       programmer
634         engineer
635            other
636         educator
637            other
638         engineer
639        librarian
640          student
641          student
642          student
643        scientist
644          retired
645       programmer
646          student
647         educator
648         engineer
649          student
650         engineer
651          retired
652            other
653        executive
654          student
655       healthcare
656         educator
657             none
658       programmer
659         educator
660          student
661       programmer
662        librarian
663            other
664         engineer
665    administrator
666    administrator
667        librarian
668           writer
669            other
670       technician
671       programmer
672    administrator
673         educator
674          student
675            other
676       programmer
677            other
678         educator
679          student
680           lawyer
681        marketing
682       programmer
683        librarian
684          student
685        librarian
686         educator
687       healthcare
688    administrator
689            other
690         salesman
691         educator
692         engineer
693       healthcare
694       programmer
695           writer
696            other
697            other
698       programmer
699            other
700          student
701        librarian
702            other
703         educator
704        librarian
705          student
706          student
707        librarian
708        homemaker
709            other
710          student
711          student
712          student
713            other
714         engineer
715       technician
716    administrator
717       technician
718       technician
719            other
720    administrator
721    entertainment
722        homemaker
723        executive
724        executive
725          student
726    administrator
727          student
728        executive
729          student
730        scientist
731         educator
732            other
733            other
734            other
735       healthcare
736           writer
737       programmer
738       technician
739       technician
740         educator
741           writer
742          student
743       programmer
744        marketing
745           writer
746         engineer
747            other
748    administrator
749            other
750    administrator
751            other
752          retired
753         salesman
754        librarian
755         educator
756             none
757          student
758          student
759          student
760            other
761          student
762    administrator
763        scientist
764         educator
765          student
766            other
767         engineer
768    administrator
769        executive
770          student
771          student
772           writer
773          student
774          student
775        executive
776        librarian
777       programmer
778          student
779          student
780       programmer
781          student
782           artist
783        marketing
784    administrator
785         engineer
786         engineer
787          student
788    administrator
789            other
790       technician
791         educator
792       programmer
793          student
794         educator
795       programmer
796           writer
797            other
798           writer
799    administrator
800       programmer
801           writer
802    administrator
803    administrator
804         educator
805            other
806        marketing
807       healthcare
808         salesman
809        marketing
810            other
811         educator
812       technician
813          student
814            other
815            other
816            other
817          student
818        librarian
819    administrator
820          student
821         engineer
822        librarian
823           artist
824            other
825         engineer
826           artist
827         engineer
828        librarian
829           writer
830       programmer
831            other
832       technician
833           writer
834            other
835        executive
836           artist
837           artist
838          student
839    entertainment
840           artist
841           doctor
842           writer
843        librarian
844         engineer
845           doctor
846           lawyer
847          student
848         engineer
849          student
850       technician
851            other
852    administrator
853           writer
854          student
855        librarian
856        marketing
857    administrator
858         educator
859            other
860          retired
861          student
862        executive
863          student
864       programmer
865           artist
866            other
867        scientist
868       programmer
869          student
870          student
871        executive
872          student
873    administrator
874        scientist
875          student
876            other
877            other
878         educator
879    administrator
880          student
881        marketing
882         engineer
883        librarian
884         engineer
885            other
886          student
887          student
888        scientist
889       technician
890          student
891    administrator
892            other
893          student
894         educator
895        librarian
896           writer
897            other
898        homemaker
899            other
900          retired
901        executive
902           artist
903         educator
904          student
905            other
906        librarian
907            other
908        librarian
909         educator
910       healthcare
911           writer
912            other
913          student
914            other
915    entertainment
916         engineer
917          student
918        scientist
919            other
920           artist
921          student
922    administrator
923          student
924            other
925         salesman
926    entertainment
927       programmer
928          student
929        scientist
930        scientist
931         educator
932         educator
933          student
934         engineer
935           doctor
936            other
937         educator
938       technician
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, dtype: object

### Step 12. How many different occupations are in this dataset?

In [16]:
#len(users['occupation'].unique())
users['occupation'].value_counts().nunique()

19

### Step 13. What is the most frequent occupation?

In [65]:
users['occupation'].value_counts().head(1)

student    196
Name: occupation, dtype: int64

### Step 14. Summarize the DataFrame.

In [19]:
users.describe()
#users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

### Step 15. Summarize all the columns

In [21]:
users.describe(include='all')
#users.dtypes

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [26]:
users['occupation'].describe()
#users['occupation'].dtypes

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [69]:
users['age'].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [28]:
pd.set_option('display.max_rows',None)
users['age'].value_counts(ascending = True).head(5)

7     1
66    1
73    1
10    1
11    1
Name: age, dtype: int64